using UnityEngine;

/// <summary>
/// When the player enters this trigger, plays the TV-static → black transition and then loads the scene.
/// No interaction needed. Put on a GameObject with a Collider that has "Is Trigger" enabled.
/// All the visuals are generated by <see cref="T_StaticTransition"/> at runtime, so there is nothing else to wire.
/// </summary>
[RequireComponent(typeof(Collider))]
public class T_StaticSceneTransition : MonoBehaviour
{
    [Header("Scene")]
    [Tooltip("Exact name of the scene to load. It must be added to File > Build Settings.")]
    [SerializeField] private string sceneToLoad;
    [SerializeField] private string playerTag = "Player";

    [Header("Timing (seconds)")]
    [Tooltip("Static fades in over the game.")]
    [SerializeField] private float staticInDuration = 0.25f;
    [Tooltip("How long the full static holds on screen.")]
    [SerializeField] private float staticHoldDuration = 0.6f;
    [Tooltip("Black closes over the static.")]
    [SerializeField] private float fadeToBlackDuration = 0.8f;
    [Tooltip("After the new scene loads, black fades away to reveal it.")]
    [SerializeField] private float fadeInDuration = 0.6f;

    [Header("Static look")]
    [Tooltip("Noise texture width in pixels (height is 16:9). Lower = chunkier static and cheaper.")]
    [SerializeField] private int noiseResolution = 320;
    [Range(0f, 1f)]
    [Tooltip("How opaque the static is over the game before it goes black.")]
    [SerializeField] private float staticOpacity = 1f;

    [Header("Audio (optional)")]
    [Tooltip("Looping static hiss to play during the transition.")]
    [SerializeField] private AudioClip staticSound;

    private bool _started;

    private void OnTriggerEnter(Collider other)
    {
        if (_started || !other.CompareTag(playerTag)) return;

        if (string.IsNullOrEmpty(sceneToLoad))
        {
            Debug.LogError("T_StaticSceneTransition: Scene name is empty!", this);
            return;
        }

        _started = true;
        T_StaticTransition.Play(sceneToLoad, staticInDuration, staticHoldDuration,
            fadeToBlackDuration, fadeInDuration, noiseResolution, staticOpacity, staticSound);
    }
}
